---
# tasks file for hswong3i.nfs_exports

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "directory"
  with_items: "{{ nfs_exports }}"
  notify: restart nfs
  tags: hswong3i.nfs_exports

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/exports.j2", dest: "/etc/exports", owner: "root", group: "root", mode: "0644" }
  notify: restart nfs
  tags: hswong3i.nfs_exports
