---
# handlers file for hswong3i.nfs_export

- name: restart nfs
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "nfs-kernel-server", state: "restarted" }
